### ISSUE TITLE
Resetting wifi-connect

### ISSUE THREAD

**Issue by Maoie86** [resin-io/resin-wifi-connect#164] opened 2018-01-27 01:25 UTC
I was able to login to the captured portal and input ssid and password.  Then I was able to connect to my wifi.  I wanted to reset so it so can connect to another wifi.  I went to the host os and delete my wifi connection using nmcli con delete.  I tried to connect to again but this time the captured portal does not appear.  My mobile phone wants me to login but there is only a blank page.  Nowhere to enter ssid and passord. 

Is there a way to reset wifi-connect to the original/clean config? 

Thanks! 

Maoie

**Comment by Maoie86** [comment] 2018-01-27 02:12
Also, what happened to the --clear command line option?

**Comment by majorz** [comment] 2018-01-27 09:16
Can you please provide me with more details: 1. OS version 2. board type 3. wireless device type (if external). Also if you are running a device on top of resinOS, if it is possible, can you please provide support access to me, so that I can investigate further? In the meantime I will try to reproduce locally with the devices I have.

**Comment by majorz** [comment] 2018-01-27 09:18
You may find more information on why the `--clear` flag is not used anymore in the PR of v4.0.0 here: https://github.com/resin-io/resin-wifi-connect/pull/157

**Comment by Maoie86** [comment] 2018-01-28 01:14
1. OS Version : Resin OS 2.7.8+rev1 (prod)
2. Raspberry Pi 3
3. Built In Wifi device

I was able to workaround it by specifying the web UI path parameter. It now gives me the captured portal.  But only a blank page if I remove the UI path parameter.

**Comment by majorz** [comment] 2018-01-28 09:01
Thanks for the clarification! The `ui` folder has to be inside the working directory where the application is executed from. The WORKDIR instruction of the Dockerfile of the application container can be used for setting this.

The issue is an instance of https://github.com/resin-io/resin-wifi-connect/issues/159 which will be fixed soon.  Closing in favor of it.

**Closed by majorz** 2018-01-28 09:01 UTC

**Comment by Maoie86** [comment] 2018-01-29 01:05
oh ok. thanks! :)

**Comment by majorz** [comment] 2018-01-29 08:56
Thanks for reporting this ;)
