### ISSUE TITLE
How to deploy this on Kali Linux on RPi3?

### ISSUE THREAD

**Issue by OffS3c** [resin-io/resin-wifi-connect#152] opened 2017-12-31 11:47 UTC
How to deploy this on Kali Linux on RPi3? 
I tried editing script raspbian-install.sh and commented OS check.
It installed and ran but its giving dbus error messages now.
What should I try next to make it work?

`root@kali:/tmp# wifi-connect 

WiFi device: wlan0
[network_manager::dbus_api:ERROR] D-Bus get 'org.freedesktop.NetworkManager.AccessPoint'::'Flags' property failed on '/org/freedesktop/NetworkManager/AccessPoint/1': wrong property type

[wifi_connect:ERROR] Getting access points failed: D-Bus get 'org.freedesktop.NetworkManager.AccessPoint'::'Flags' property failed on '/org/freedesktop/NetworkManager/AccessPoint/1': wrong property type

root@kali:/tmp# 
`

**Comment by majorz** [comment] 2018-01-02 09:27
This is due to a bug in the NetworkManager bindings which is triggered by NetworkManager 1.10+. It will be fixed in the upcoming new release: https://github.com/resin-io-modules/network-manager/issues/106

**Comment by OffS3c** [comment] 2018-01-02 19:42
okay great i'll be testing the new release 👍

**Comment by majorz** [comment] 2018-01-11 13:28
@OffS3c the issue is fixed now. Please let me know in case you encounter any issues with it.

**Closed by majorz** 2018-01-11 13:28 UTC
